trigger:
 - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
# this is job name
 - task: Docker@2
   displayName: Build an image
   inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

     
