trigger:
- feature-1

stages:
- stage: Build # This is the name of the stage
  displayName: 'Build Stage' # This is a human-readable name for the stage

  jobs:
  - job: BuildJob # this is the name of the job
    displayName: 'Build Job' # This is a friendly name for the job,

    steps: # Steps are individual tasks or commands executed as part of a job
    - script: | # This block contains shell commands
        echo "Building the project..."
        # # Add your build commands here
        # mkdir $(Build.ArtifactStagingDirectory)
        # echo "Sample Build Output" > $(Build.ArtifactStagingDirectory)/output.txt
      displayName: 'Build project' #his is a name for this specific step