trigger:
 - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
# this is job name
#  - task: Docker@2
#    displayName: Build an image
#    inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile

 - task: Docker@2
# this is a job name
   displayName: Buils and push image
   inputs:
     containerRegistry: 'azure-docker-conn'
     repository: 'sewalal/myimg'
     command: 'buildAndPush'
     Dockerfile: 'app/Dockerfile'
     tags: '0.1.0'
     buildContext: 'app'
